version: '3'

services:
  mybot:
    image: afnastya/missing_semester_homework:latest
    labels:
      - "com.centurylinklabs.watchtower.scope=myscope"
    environment:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --scope myscope
    labels:
      - "com.centurylinklabs.watchtower.scope=myscope"