name: CI/CD

on: push

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y python3.8 python3-pip
          pip3 install pylint pyTelegramBotAPI
      - name: Pylint check
        run: pylint *.py --disable=missing-docstring
  push-image:
    needs: check
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1.12.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build & push Docker image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: mybot:latest
