name: Testing

on:
  push:
    branches:
      - 'main'

jobs:
  linter-check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y python3.8 python3-pip
          pip3 install pylint pyTelegramBotAPI
      - name: Pylint check
        run: pylint *.py --disable=missing-docstring
      
      - name: Create a release
        if: ${{ success() }}
        run: |
          curl \
          -X POST \
          -H https://api.github.com/repos/afnastya/MissingSemesterHomework/releases
