name: CI/CD

on:
  push:
    branches:
      - 'main'

jobs:
  linter-check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y python3.8 python3-pip
          pip3 install pylint pyTelegramBotAPI
      - name: Pylint check
        run: pylint *.py --disable=missing-docstring

  push-docker-image:
    needs: 
      linter-check:
        result: success
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1.12.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build & push Docker image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/missing_semester_homework:latest
